language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:canonical-qt5-edgers/qt5-beta-proper
  - sudo apt-get update -qq
  - sudo apt-get dist-upgrade -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev

before_script:
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - false

script:
  - make
  - make check
